/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        background: '#f8f9ff',
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#424656',
        'outline-variant': '#c2c6d8',
        outline: '#727687',
        primary: '#0050cb',
        'primary-container': '#0066ff',
        'primary-fixed': '#dae1ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#f8f7ff',
        secondary: '#49607e',
        'secondary-container': '#c4dcff',
        tertiary: '#005e90',
        'tertiary-container': '#0078b6',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        success: '#10b981',
        warning: '#f97316',
        navy: '#0a2540',
        sky: '#0284c7',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans Variable', 'Plus Jakarta Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['Newsreader Variable', 'Newsreader', 'Georgia', 'serif'],
        mono: ['JetBrains Mono Variable', 'JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        gutter: '1.5rem',
        'gutter-mobile': '0.75rem',
        margin: '2rem',
        'margin-mobile': '1rem',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      boxShadow: {
        card: '0 1px 3px rgba(10, 37, 64, 0.06)',
        raised: '0 10px 24px rgba(10, 37, 64, 0.10)',
      },
    },
  },
}
